### PR TITLE
Truncate ldif password file before updating

### PR DESCRIPTION
**Pull request by vokac**

### CODE REVIEW

**Comment by gwarf** [comment]
HI @vokac,
Thanks, could you please provide some description/context/justification for this PR?

Please also fix line length: https://travis-ci.org/EGI-Foundation/bdii/jobs/579576902#L770

**Comment by gwarf** [comment]
Hi @vokac,
Still some errors on flake8 with python 2.7, please have a look: https://travis-ci.org/EGI-Foundation/bdii/jobs/579812194#L773 .

**Comment by gwarf** [comment]
Oh, it's outside of your commit, it's a bit weird, it seems something changed for flake8 on python 2.7. Let us know if you can have a look otherwise we will try.

**Comment by vokac** [comment]
Without truncating existing file and new shorter password you'll get content that contain new password + remaining characters from old password.

**Comment by gwarf** [comment]
@vokac can you please allow me to commit on your PR?
https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Otherwise the following around line `393` should be enough to fix the tests:
```diff
            # If the old entries are different find the modify.
            if not new_entry[attribute] == old_entry[attribute]:
-                   replace_attribute[attribute] = new_entry[attribute]
+               replace_attribute[attribute] = new_entry[attribute]
```

**Comment by vokac** [comment]
All flake8 issues blocking this merge request should be now fixed

**Review by gwarf — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
