### PR TITLE
Prepare new release 6.0.0

### PR DESCRIPTION
**Pull request by gwarf**
Prepare new release.
Suggesting to use version 6.0.0 due to changes related to ldap and python3.
I've removed the debian files as they are not used, not maintained/aligned with what is in debian repositories, and it's better to reference the one maintained by you @ellert.
I've documented installing on RHEL-like systems from UMD or EPEL.

### CODE REVIEW

**Comment by gwarf** [comment]
Does this look ok to you @ellert ?

**Review by ellert — APPROVED** [review]
LGTM.

**Comment by ellert** [comment]
BDII 6.0.0 is available in EPEL testing:

EPEL 7:
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2022-63b74d8dae

EPEL 8:
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2022-a2904bc928

EPEL 9:
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2022-aaa0469d77

The EPEL 8 and EPEL 9 updates to BDII 6 do not contain major changes since the changes were already present in the previous version using patches in the source RPM.

However, the EPEL 7 update is a major change since this changes from python 2 to python 3 in this case.

I have disabled the automatic push to stable due to time spent in testing for the EPEL 7 update. Please provide feedback.

**Comment by gwarf** [comment]
Indeed, currently there have been much/any test done with this packages using python3.

Our intention is to release the new packages versions as part of UMD5 (for all the BDII-related packages and components), and looking with the UMD team how to leverage the automatic testing and quality assurance they have in place. I understood they should be able to sooner provide some preview repository, and also a way to start integrating with their automated testing infra. Then we can see if some early adopters can help in testing those packages on their side.

**Pull request merged**
