### PR TITLE
fix: updated log.warn to log.warning

### LINKED ISSUE #53: Deprecation warning for /usr/sbin/bdii-update
# Short Description of the issue

This is on a Rocky Linux release 9.4 (Blue Onyx) site bdii installed from epel. The bdii-update.log is filled with depreciation warnings, making it hard to see any real errors. The actual running of the bdii is unaffected.

```
[root@bdii02 ~]# tail /var/log/bdii/bdii-update.log
/usr/sbin/bdii-update:552: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  log.warn(line.strip())
 ```

# Summary of proposed changes
The fix (replace 'warn' by 'warning') is straight forward and gets rid of  this spurious error message.

### PR DESCRIPTION
**Pull request by marianne013**
# Summary

Replaces log.warn with the python standard log.warning

---

**Related issue :**

fixes #53

### CODE REVIEW

**Comment by gwarf** [comment]
An update: I aim at publishing a new BDII release at the end of next week, in case implementing additional tests have not been possible, I will just merge this PR as it is.

**Comment by marianne013** [comment]
If it's any consolation we've been running this code for weeks at our site.

**Comment by gwarf** [comment]
Definitely good to hear, thanks @marianne013.
Sorry again for the delay to handle this.

**Review by gwarf — APPROVED** [review]
LGTM.
Thanks, will merge, we can add test later when time permits.

**Pull request merged**
