### PR TITLE
Python 3

### PR DESCRIPTION
**Pull request by ellert**
The current version requires additional encode/decode for python 3 due to the base64 change.
This PR is a rebase of #15 with the additional changes added.

### CODE REVIEW

**Comment by gwarf** [comment]
Thanks @ellert !
Would you mind also updating the python 3 dependency in the spec and where it makes sense?

**Comment by gwarf** [comment]
So travis tests are failing, but we also would like to move to GitHub actions, let's see if we can manage to do this quickly and use this to test this PR.

**Comment by gwarf** [comment]
OK so now linting with GitHub Actions is working, I will try to push changes to this PR for doing tests/building with CentOS 8.

**Review by andrea-manzi — APPROVED** [review]
thanks! it looks quite clean to me, and aligned now to what is in EPEL

**Pull request merged**
