### PR TITLE
Updated for Python 3

### PR DESCRIPTION
**Pull request by lfield**

### CODE REVIEW

**Comment by gwarf** [comment]
Thanks a lot @lfield!

Please check linting errors: https://travis-ci.org/EGI-Foundation/bdii/jobs/584522172#L775

**Comment by ellert** [comment]
Here are some additional changes suggested by python-modernize:
[0001-Changes-suggested-by-python-modernize.patch.txt](https://github.com/EGI-Foundation/bdii/files/3611447/0001-Changes-suggested-by-python-modernize.patch.txt)

**Comment by lfield** [comment]
I have updated to address the python-modernize suggestions.

**Comment by gwarf** [comment]
OK so it seems we will most probably move to python 3 support for the BDII, using python 3 from EPEL on CentOS 6 and CentOS 7.
So to merge this PR we need to have all the packaging and other stuff ready for python 3.
If you give us write access to the PR we can try to participate too: https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by lfield** [comment]
Edits are allowed from maintainers. Not that Mattias has already patched Fedora with this PR.

**Comment by gwarf** [comment]
OK, didn't realise @ellert was managing packages in EPEL.
Still it's a bit weird to have a package with extra patches instead of using the code from the official repo and either using a different version number of having additional patches with the same main version.

**Comment by gwarf** [comment]
Thanks for this @lfield, but unfortunately it stalled and as @ellert made an updated PR in #25 I will close yours.

**Comment by lfield** [comment]
Should you not mark the new PR as duplicate and use this one?

**Comment by gwarf** [comment]
The new one was including a few more additional differences and up to date with the master, so thought it would be easier to go forward with it.
Sorry, wasn't willing to be harsh/painful, your contribution was very welcome.

**Comment by lfield** [comment]
Leaving it open for over a year and closing like this is not correct in terms of Git etiquette. The required addition changes could have been requested in this PR. I will not block as supporting CentOS 8 is more important than my crushed ego. :)

**Comment by gwarf** [comment]
I reckon I made an error sorry, I overlooked this PR and acted too quickly when closing in favour of the new one, my bad.
Please don't refrain from making more PR, I will do my best to handle them more cleanly. :)

**Comment by gwarf** [comment]
For the record as CentOS 6 is now expected to be a thing from the past, we agreed to finally moved to supporting only python3 and drop CentOS 6 support.
For CentOS 8 we discussed with UMD Release Team that we will probably build an openldap-server package that will be pushed to UMD as a dependency.

**Comment by lfield** [comment]
Good. I did look into releasing openldap-servers in EPEL and was in contact with the package maintainer. In any case I am sure that Mattias Ellert is well placed to make such a decision. Let me know if you need any pre-prod testing once a repository is available.

**Comment by gwarf** [comment]
Initially I've looked for various packaging initiatives for this and [LDAP Tool Box](https://github.com/ltb-project/openldap-rpm) was one of the most cleanly looking.
Then we discussed pushing a home-made package to UMD and @msalle put in place some building for openldap-server: https://copr.fedorainfracloud.org/coprs/msalle/OpenLDAP/.

But I feel like a version in EPEL would be the ideal solution and trigger the most participation/interest/usage.

**Comment by lfield** [comment]
This is now off-topic so we should shift this discussion to an issue. 
As far as I can tell the Fedora build automatically creates the server package.

https://koji.fedoraproject.org/koji/buildinfo?buildID=1645917

So someone would just need to join the package maintainers and kick off a build for EPEL 8.

https://bodhi.fedoraproject.org/updates/?search=openldap

@ellert probably has the highest reputation and would be best placed to do this.

**Comment by gwarf** [comment]
Let's move to https://github.com/EGI-Foundation/bdii/issues/13#issuecomment-737250912

**Pull request closed without merging**
